#!/bin/bash
#
# YSFReflector FULLY Automated Installation Script - NGINX Version
# By AJ6EE - Bare metal installation with nginx
#
# Usage: ./ysf-nginx-install.sh CALLSIGN "DESCRIPTION" [PORT] [TIMEZONE]
# Example: ./ysf-nginx-install.sh AJ6EE "Kevin's YSF Node" 42000 "America/Los_Angeles"
#

set -e  # Exit on any error

# Color output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

print_status() { echo -e "${GREEN}[*]${NC} $1"; }
print_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Check arguments
if [ "$#" -lt 2 ]; then
    echo "Usage: $0 CALLSIGN \"DESCRIPTION\" [PORT] [TIMEZONE]"
    echo "Example: $0 AJ6EE \"Kevin's YSF Node\" 42000 \"America/Los_Angeles\""
    echo ""
    echo "Common Timezones:"
    echo "  America/Los_Angeles (Pacific)"
    echo "  America/Denver (Mountain)"
    echo "  America/Chicago (Central)"
    echo "  America/New_York (Eastern)"
    echo "  UTC (Universal Time)"
    exit 1
fi

# Check if running as root
if [[ $EUID -ne 0 ]]; then
   print_error "This script must be run as root"
   echo "Please run: sudo bash $0 $@"
   exit 1
fi

CALLSIGN="$1"
DESCRIPTION="$2"
PORT="${3:-42000}"
TIMEZONE="${4:-UTC}"

# Truncate description if needed
if [ ${#DESCRIPTION} -gt 18 ]; then
    DESCRIPTION="${DESCRIPTION:0:18}"
fi

echo "==========================================="
print_status "YSFReflector Installation with nginx"
echo "==========================================="
echo ""
echo "  Callsign: $CALLSIGN"
echo "  Description: $DESCRIPTION"
echo "  Port: $PORT"
echo "  Timezone: $TIMEZONE"
echo ""

WORK_DIR="/root/YSFReflector"
mkdir -p "$WORK_DIR"
cd "$WORK_DIR"

# Install dependencies
print_status "Installing nginx, PHP, and build tools..."
apt-get update -qq
apt-get install -y \
    nginx \
    php-fpm \
    php-cli \
    git \
    build-essential \
    wget

print_status "Dependencies installed"

# Detect PHP version
PHP_VERSION=$(php -r 'echo PHP_MAJOR_VERSION.".".PHP_MINOR_VERSION;')
print_status "Detected PHP version: ${PHP_VERSION}"

# Download and run installer
print_status "Downloading and building YSFReflector..."
if [ ! -f install.sh ]; then
    wget -q https://register.ysfreflector.de/install.sh
    chmod +x install.sh
fi

# Run the installer (it prompts for name and description)
bash ./install.sh <<EOF
$CALLSIGN
$DESCRIPTION
EOF

print_status "YSFReflector binary built successfully"

# Fix init script
if [ -f /etc/init.d/YSFReflector.sh ]; then
    mv /etc/init.d/YSFReflector.sh /etc/init.d/YSFReflector
    chmod +x /etc/init.d/YSFReflector
fi

# Clone Dashboard
print_status "Installing YSFReflector Dashboard..."
if [ -d YSFReflector-Dashboard ]; then
    rm -rf YSFReflector-Dashboard
fi
git clone -q https://github.com/dg9vh/YSFReflector-Dashboard.git

print_status "Copying Dashboard files to web root..."
rm -rf /var/www/html/*
cp -R YSFReflector-Dashboard/* /var/www/html/

# Configure nginx
print_status "Configuring nginx..."
cat > /etc/nginx/sites-available/default <<'NGINXCONF'
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.php index.html index.htm;

    server_name _;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.ht {
        deny all;
    }
}
NGINXCONF

# Update YSFReflector.ini with user's settings
print_status "Configuring YSFReflector.ini..."
if [ -f /root/YSFReflector/YSFReflector.ini ]; then
    sed -i "s/^Name=.*/Name=$CALLSIGN/" /root/YSFReflector/YSFReflector.ini
    sed -i "s/^Description=.*/Description=$DESCRIPTION/" /root/YSFReflector/YSFReflector.ini
    sed -i "s/^FileLevel=.*/FileLevel=1/" /root/YSFReflector/YSFReflector.ini
    sed -i "s/^Port=.*/Port=$PORT/" /root/YSFReflector/YSFReflector.ini
    
    # Move to /etc if not already there
    if [ ! -f /etc/YSFReflector.ini ]; then
        cp /root/YSFReflector/YSFReflector.ini /etc/
    fi
fi

print_status "Updated configuration file"

# Create Dashboard config directory
print_status "Configuring Dashboard..."
mkdir -p /var/www/html/config

# Create the config.php file directly (no web setup needed!)
cat > /var/www/html/config/config.php <<CONFIGEOF
<?php
// YSFReflector Dashboard Configuration
// Auto-generated by AJ6EE installation script

date_default_timezone_set('${TIMEZONE}');

define("YSFREFLECTORLOGPATH", "/var/log/YSFReflector");
define("YSFREFLECTORLOGPREFIX", "YSFReflector");
define("YSFREFLECTORINIPATH", "/etc/");
define("YSFREFLECTORINIFILENAME", "YSFReflector.ini");
define("YSFREFLECTORPATH", "/usr/local/bin/");

define("TIMEZONE", "${TIMEZONE}");
define("LOGO", "");
define("REFRESHAFTER", "60");
define("SHOWOLDMHEARD", "0");
define("TEMPERATUREHIGHLEVEL", "60");
define("TEMPERATUREALERT", "");
define("TEMPCPUIDALERT", "");
define("LOADHIGHLEVEL", "100");
define("LOADALERT", "");
define("SHOWPROGRESSBARS", "on");
define("SHOWPIP", "off");
define("DISABLESETUPWARNING", "");
?>
CONFIGEOF

print_status "Dashboard configuration created"

# Remove setup.php for security
if [ -f /var/www/html/setup.php ]; then
    rm /var/www/html/setup.php
    print_status "Removed setup.php for security"
fi

# Set proper permissions
chown -R www-data:www-data /var/www/html
mkdir -p /var/log/YSFReflector
chown -R www-data:www-data /var/log/YSFReflector

# Start/restart services
print_status "Starting services..."

# Restart nginx
systemctl restart nginx
systemctl enable nginx

# Start YSFReflector service
if [ -f /etc/init.d/YSFReflector ]; then
    /etc/init.d/YSFReflector start || true
fi

sleep 2

# Get IP address
IP_ADDR=$(hostname -I | awk '{print $1}')

# Verify services are running
NGINX_RUNNING=false
YSF_RUNNING=false

if systemctl is-active --quiet nginx; then
    NGINX_RUNNING=true
    print_status "nginx is running"
else
    print_error "nginx may not have started properly"
fi

if ps aux | grep -v grep | grep YSFReflector > /dev/null; then
    YSF_RUNNING=true
    print_status "YSFReflector is running"
else
    print_error "YSFReflector may not have started properly"
fi

echo ""
echo "==========================================="
print_status "Installation Complete!"
echo "==========================================="
echo ""
echo "Your YSFReflector node is now running!"
echo ""
echo "  Dashboard URL: http://$IP_ADDR/"
echo "  Callsign: $CALLSIGN"
echo "  Description: $DESCRIPTION"
echo "  Port: $PORT"
echo "  Timezone: $TIMEZONE"
echo ""
echo "  Web Server: nginx"
echo "  PHP Version: $PHP_VERSION"
echo ""
echo "Useful commands:"
echo "  nginx status:  systemctl status nginx"
echo "  nginx restart: sudo systemctl restart nginx"
echo "  YSF status:    sudo /etc/init.d/YSFReflector status"
echo "  YSF restart:   sudo /etc/init.d/YSFReflector restart"
echo "  View logs:     tail -f /var/log/YSFReflector/*.log"
echo ""
echo "Next steps:"
echo "  1. Open browser to: http://$IP_ADDR/"
echo "  2. Register at: https://register.ysfreflector.de/"
echo "  3. Forward port $PORT (TCP/UDP) on your router"
echo ""
print_status "73 de AJ6EE"
